### PR TITLE
fixed default path discrepancy, added comment

### LINKED ISSUE #1247: management socket default in ph-cli differs from ph.
On ubuntu, when I run ph, it defaults to setting it's management socket in a location but that location is not the default when I run ph-cli.

Output from ph:
```
2026-03-03T16:20:29.398791Z  INFO startup: control socket bound to "/root/.local/share/zpr/control.sock"
2026-03-03T16:20:29.398877Z  INFO startup: capture socket bound to "/root/.local/share/zpr/capture.sock"
```

Output from ph-cli:
```
Options:
  -p, --socket <SOCKET>          Path to the Packet Handler's management socket [default: /var/run/zpr/ph.sock]
```

These should be the same.

### PR DESCRIPTION
**Pull request by owenrhysthomas**
Changed socket to PathBuf so we could use the exact same function logic as in the config. Changed cap-socket to align with socket.

### CODE REVIEW

File: adapter/cli/src/main.rs [hunk 1]
```diff
@@ -66,18 +67,19 @@ impl From<std::str::Utf8Error> for CliError {
 async fn main() -> Result<(), CliError> {
     let args = CmdlineArgs::parse();
     let socket = args.socket.clone();
+    println!("{:?}", socket);
```
Comment (mkolehmainen) [inline adapter/cli/src/main.rs]: Is this printf left in by accident?

**Review by mkolehmainen — DISMISSED** [review]
Looks good. Remove the println?

**Review by mkolehmainen — APPROVED** [review]
LGTM!
