### PR TITLE
Fuzz testing for filter and validate

### LINKED ISSUE #321: [cbpf-rs] fuzz testing
The idea here is to use [cargo-fuzz](https://rust-fuzz.github.io/book/cargo-fuzz/tutorial.html) to generate random-ish inputs to the `cbpf-rs` engine, ensuring that no combinations make it crash.  The trick is it has two inputs: the program and the data, whereas fuzzing just gives a single input.  I think the structure-aware fuzzing stuff (section 1.4 of that manual) talks about mechanisms to split the input up into pieces (the `Arbitrary` trait).  And the program would have to be "decoded" from the fuzzer string also, which I think can make use of that.

### PR DESCRIPTION
**Pull request by owenrhysthomas**

### CODE REVIEW

**Comment by owenrhysthomas** [comment]
Currently the validate fuzz test has yet to fail, but the filter one does. I can't figure out where in the filter function it's failing.

File: cbpf-rs/src/lib.rs [hunk 1]
```diff
@@ -147,7 +148,16 @@ pub enum BpfError {
...
+#[derive(Debug)]
+#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
+pub struct FuzzIn {
+    pub insn: Vec<BpfInsn>,
+    pub pkt: Vec<u8>,
+}
+
 /// a validated BPF program
+// #[derive(Debug)]
+// #[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
```
Comment (cpacejo) [inline cbpf-rs/src/lib.rs]: What you have with `FuzzIn` looks correct to me ­– since `BpfProgram` is only created by `validate()`, we won't be creating it from fuzz data, so you can safely remove these commented-out derives.

File: cbpf-rs/Cargo.toml
Comment (cpacejo) [inline cbpf-rs/Cargo.toml:1]: I think under `[features]` you can add `arbitrary = ["dep:arbitrary"]`, which will automatically enable the `arbitrary` dependency when that feature is enabled.

(Though actually I'm surprised everything builds as-is so maybe Cargo is automatically/implicitly adding that line?)

File: cbpf-rs/fuzz/Cargo.toml [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+[package.metadata]
+cargo-fuzz = true
+
+[dependencies]
+libfuzzer-sys = "0.4"
+cbpf-rs = { path = "..", features = ["arbitrary"] }
+
+#[dependencies.cbpf-rs]
+#path = ".."
+#features = ["arbitrary"]
```
Comment (cpacejo) [inline cbpf-rs/fuzz/Cargo.toml]: Right, I think what you have above is correct!

File: cbpf-rs/src/lib.rs [hunk 3]
```diff
@@ -147,7 +148,16 @@ pub enum BpfError {
     DivideByZero,
 }
 
+#[derive(Debug)]
+#[cfg_attr(feature = "arbitrary", derive(arbitrary::Arbitrary))]
```
Comment (cpacejo) [inline cbpf-rs/src/lib.rs]: Actually on this one I would just make the whole thing only present if `arbitrary` is enabled, since it's only used for fuzz testing.  So e.g.:
```
#[cfg(feature = "arbitrary")]
#[derive(arbitrary::Arbitrary)]
```

(But for the other structs yes that is exactly what I was thinking!)

**Review by cpacejo — APPROVED** [review]
This is so very exciting!!!  I can't wait to dig into the bug(s) it found hahaha.

Just a couple trivial cleanups, feel free to push after addressing, but otherwise this looks perfect!

**Comment by cpacejo** [comment]
Oh!  Looks like there is a `cfg(fuzzing)` we can use instead of `cfg(feature = "arbitrary")`, which is provided by `cargo fuzz`: https://rust-fuzz.github.io/book/cargo-fuzz/guide.html

BTW here is the first example my run found:
```
$ cargo fuzz fmt filter fuzz/artifacts/filter/crash-ac3420c4a04d01a81e12b4ee3e8f26443c89021d

Output of `std::fmt::Debug`:

FuzzIn {
    insn: [
        BpfInsn {
            code: 33,
            jt: 255,
            jf: 255,
            k: 4278910975,
        },
        BpfInsn {
            code: 6,
            jt: 0,
            jf: 10,
            k: 0,
        },
    ],
    pkt: [],
}
```

This is very exciting!!!

**Comment by cpacejo** [comment]
& was able to get a useful backtrace like this:
```
$ RUST_BACKTRACE=1 cargo fuzz run filter fuzz/artifacts/filter/crash-ac3420c4a04d01a81e12b4ee3e8f26443c89021d 
    Finished `release` profile [optimized + debuginfo] target(s) in 0.01s
    Finished `release` profile [optimized + debuginfo] target(s) in 0.01s
     Running `fuzz/target/x86_64-unknown-linux-gnu/release/filter -artifact_prefix=/home/cpacejo/projects/zpr-core-wt/cbpf-rs/fuzz/artifacts/filter/ fuzz/crash-ac3420c4a04d01a81e12b4ee3e8f26443c89021d`
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 4102125516
INFO: Loaded 1 modules   (7786 inline 8-bit counters): 7786 [0x5624e8e52bd0, 0x5624e8e54a3a), 
INFO: Loaded 1 PC tables (7786 PCs): 7786 [0x5624e8e54a40,0x5624e8e730e0), 
fuzz/target/x86_64-unknown-linux-gnu/release/filter: Running 1 inputs 1 time(s) each.
Running: fuzz/crash-ac3420c4a04d01a81e12b4ee3e8f26443c89021d
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
unsafe precondition(s) violated: hint::unreachable_unchecked must never be reached
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/panicking.rs:112:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/panicking.rs:122:5
   3: core::panicking::panic_nounwind
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/panicking.rs:221:5
   4: core::hint::unreachable_unchecked::precondition_check
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/ub_checks.rs:68:21
   5: core::hint::unreachable_unchecked
             at /rustc/8bfcae730a5db2438bbda72796175bba21427be1/library/core/src/ub_checks.rs:75:17
   6: cbpf_rs::BpfProgram::filter_slice
             at ./src/lib.rs:386:31
   7: cbpf_rs::BpfProgram::filter
             at ./src/lib.rs:204:9
```

**Comment by cpacejo** [comment]
Opened https://github.com/org-zpr/zpr-core/pull/348 with fixes for the bugs fuzzing found!!
