### PR TITLE
recieved -> received & added handling for wrong # of args to rpc_work…

### LINKED ISSUE #186: Error handling in RPC commands
Right now if any of the RPC commands that expect multiple values, like PERF-SAMPLE or SET-CAPTURE, are not provided multiple arguments, the program simply fails with no explanation. Could send some kind of message letting them know

EDIT: Just realized this is only a problem if directly connecting to the RPC worker, if you use the debug tool it sets default values, rendering this problem mostly irrelevant.

### PR DESCRIPTION
**Pull request by owenrhysthomas**
…er comms

### CODE REVIEW

File: adapter/ph/src/main.rs [hunk 1]
```diff
@@ -202,8 +202,8 @@ fn main() -> ExitCode {
 
             let mut js = JoinSet::new();
 
-            // Launches RPC worker program
-            js.spawn(rpc_worker::launch(&*asm, &*unix_socket));
+            // // Launches RPC worker program
+            // js.spawn(rpc_worker::launch(&*asm, &*unix_socket));
```
Comment (cpacejo) [inline adapter/ph/src/main.rs]: Oh, I see this was duplicated on line 250!  Feel free to just delete no need to leave as a comment.

**Review by cpacejo — APPROVED** [review]
Looks good!
