### PR TITLE
Fix integration tests to dump stats again

### LINKED ISSUE #519: Basic-test doesn't dump stats

### PR DESCRIPTION
**Pull request by svjaffer**
Resolves #519

### CODE REVIEW

File: adapter/ph/test/basic-test.sh [hunk 1]
```diff
@@ -72,7 +71,6 @@ sudo -E ip netns exec zpr-node sudo -E -u "$ZPR_USER" "$PH_BIN" \
      --certificate-file node.crt \
      --private-key-file node.key \
      --tun-if tun0 node 2>&1 |tee node.log &
-CHILDREN=(${CHILDREN[@]} "$!")
```
Comment (svjaffer) [inline adapter/ph/test/basic-test.sh:75]: So, the basic problem was that this was getting the PID for an ephemeral process that was going away almost immediately, so issuing signals to it wasn't doing anything.

File: adapter/ph/test/basic-test.sh [hunk 2]
```diff
@@ -115,25 +111,23 @@ wait_for 5 check_carrier zpr-a tun0 || { echo "FAILURE"; exit 1; }
 wait_for 5 check_carrier zpr-b tun0 || { echo "FAILURE"; exit 1; }
 wait_for 5 check_carrier zpr-node tun0 || { echo "FAILURE"; exit 1; }
 echo "Carrier has arrived."
-
-stty sane || true
-
-
-echo "PAUSING FOR KEY MANAGEMENT EXCHANGE ..."
-countdown 10
```
Comment (svjaffer) [inline adapter/ph/test/basic-test.sh:123]: Just got rid of this because it wasn't necessary anymore.  Unrelated to the main purpose of the PR

File: adapter/ph/test/basic-test.sh [hunk 3]
```diff
@@ -155,8 +149,15 @@ done
...
 #
 
-sudo kill -SIGUSR1 "${CHILDREN[@]}" 2> /dev/null || true
-sleep 1  # FIXME: let's do something better here
+for ph in $(pgrep ph)
+do
+	echo
+	echo "Terminating $ph"
+	sleep 1
+	sudo kill -SIGTERM "$ph"
```
Comment (svjaffer) [inline adapter/ph/test/basic-test.sh]: I switched it to SIGTERM since SIGUSR1 *only* prints stats and doesn't terminate the process and since this is in the cleanup block, I figured we should be actually tearing down the processes :)

File: adapter/ph/test/basic-test.sh (hunk 1 above)
Comment (cpacejo) [reply adapter/ph/test/basic-test.sh:75]: OH BECAUSE OF THE TEE!!!!!!!!!!!!!!!!!!!!!!!!

File: adapter/ph/test/basic-test.sh (hunk 2 above)
Comment (cpacejo) [reply adapter/ph/test/basic-test.sh:123]: NICE!!!!  Was gonna ask about that haha

File: adapter/ph/test/basic-test.sh (hunk 3 above)
Comment (cpacejo) [reply adapter/ph/test/basic-test.sh]: It used to be SIGTERM, I think it got changed to SIGUSR1 while we were debugging this issue ha!

File: adapter/ph/test/basic-test.sh [hunk 4]
```diff
@@ -155,8 +149,17 @@ done
 # Cleanup
 #
 
-sudo kill -SIGUSR1 "${CHILDREN[@]}" 2> /dev/null || true
-sleep 1  # FIXME: let's do something better here
+rgid=$(($(ps -o rgid= -p "$$")))
+echo $rgid
```
Comment (cpacejo) [inline adapter/ph/test/basic-test.sh]: `echo $rgid` leftover from debugging?

**Review by cpacejo — DISMISSED** [review]
Nice work!!!!!!!!!

File: adapter/ph/test/basic-test.sh (hunk 4 above)
Comment (svjaffer) [reply adapter/ph/test/basic-test.sh]: I needed to see if it was actually different on the different github runners and it wasn't.  Basically, the first time I pushed it up, basic-test and capture-test got to this point at the same time and sniped each-others' processes and got stuck and had to be force-killed.  So I'm trying to find a way to limit it to processes in this process tree

Comment (svjaffer) [reply adapter/ph/test/basic-test.sh]: Well, I tried about a dozen more elegant ways to avoid that issue, but none of them worked so in the end I brute forced it with regex-parsing pstree.  Eh, it works.

File: adapter/ph/test/common_funcs.sh [hunk 5]
```diff
@@ -134,6 +134,13 @@ function countdown() {
     echo
 }
 
+# Get all descendant PIDs whose name matches a specific list
+function get_descendants() {
+    exenames="(ph|node|adapter)"
```
Comment (svjaffer) [inline adapter/ph/test/common_funcs.sh:139]: Only ph exists currently, but I wanted to make it very obvious how to modify this to add another process name to the list.  If someone wanted to be very fancy, they could make this function take a list of names and format them, removing the need for anyone to muck with regex strings at all.  But that's more effort than I'm willing to throw at this for now.

Comment (cpacejo) [reply adapter/ph/test/common_funcs.sh:139]: Ya if we find a better way we can fix it later!

**Review by cpacejo — APPROVED** [review]
